### ISSUE TITLE
This project can handle something more than yes/no problem

### ISSUE THREAD

**Issue by 0xaryan** [Nikronic/Female_Yes.No_Translator#1]
Wise project.
Understanding what a yes or no truly means is one of the worlds active concerns. But there are related and similar cases that should be handled too.

- Saying "Ok" when it is not actually ok in their opinion.
- Saying "You can do x" when you actually can't and never should do 'x'
- Detect a threatening or passive-aggressive talk when they look completely calm.

If we, men, could someday determine what women's answer exactly means, probably the world is getting near to its end. Until then, the most efficient solution is to solve it in a stochastic way, just like how you solved it.

**Comment by Nikronic** [comment]
I completely agree with you.
And one thing I can mention is, if any system can determine the **actual meaning** of these keywords in NLP science, this is actually **the end of NLP science**, because it does something completely better than humans (Men I mean!).

**Comment by 0xaryan** [comment]
This will be closed since this won't fix.
